<<<<<<< HEAD
# Generated by Django 5.2.15 on 2026-06-25 18:14
=======
# Generated by Django 5.2.15 on 2026-06-14 22:24
>>>>>>> 8c392a9b0dc9d25a3bcbdc05c9fd41012fd7db29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
