# Generated by Django 5.2.15 on 2026-06-14 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoqItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_items', to='api.tenders')),
            ],
        ),
        migrations.CreateModel(
            name='BoqPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('boq_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='api.boqitems')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_prices', to='api.tendersubmissions')),
            ],
        ),
        migrations.CreateModel(
            name='HumanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('dicision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_reviews', to='api.tendersubmissions')),
            ],
        ),
        migrations.CreateModel(
            name='RiskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('risk_level', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_items', to='api.tendersubmissions')),
            ],
        ),
        migrations.DeleteModel(
            name='RiskReports',
        ),
    ]
