# Generated by Django 5.2.15 on 2026-06-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_boqitems_boqprice_humanreview_riskitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderfiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tender_files/'),
        ),
        migrations.AlterField(
            model_name='tenderfiles',
            name='file_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
