# Generated by Django 5.2.15 on 2026-06-19 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tenderfiles_file_alter_tenderfiles_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenders',
            name='duration_months',
            field=models.PositiveIntegerField(default=0, help_text='Tender/project duration in months.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenders',
            name='location',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenders',
            name='project_category',
            field=models.CharField(choices=[('construction', 'Construction'), ('roads', 'Roads & Infrastructure'), ('buildings', 'Buildings'), ('electrical', 'Electrical'), ('mechanical', 'Mechanical'), ('water', 'Water & Sewage'), ('it', 'IT & Telecom'), ('consulting', 'Consulting'), ('supplies', 'Supplies & Procurement'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='other', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenders',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 1, 1)),
            preserve_default=False,
        ),
    ]
