# Generated by Django 5.2.15 on 2026-06-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tenders_duration_months_tenders_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderfiles',
            name='file_category',
            field=models.CharField(blank=True, choices=[('technical', 'Technical Proposal'), ('financial', 'Financial Proposal'), ('boq', 'BOQ'), ('certificates', 'Certificates & License')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='duration_months',
            field=models.PositiveIntegerField(),
        ),
    ]
