# Generated by Django 5.2.15 on 2026-06-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tenderfiles_file_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionfiles',
            name='extracted_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissionfiles',
            name='extracted_meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenderfiles',
            name='extracted_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenderfiles',
            name='extracted_meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenders',
            name='comparison_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenders',
            name='recommendation_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenders',
            name='structured_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tendersubmissions',
            name='financial_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tendersubmissions',
            name='justification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tendersubmissions',
            name='risk_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tendersubmissions',
            name='structured_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tendersubmissions',
            name='technical_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tendersubmissions',
            name='validation_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tendersubmissions',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('Highly Recommended', 'Highly Recommended'), ('Recommended', 'Recommended'), ('Acceptable', 'Acceptable'), ('Not Recommended', 'Not Recommended'), ('Disqualified', 'Disqualified')], max_length=20, null=True),
        ),
    ]
