# Generated by Django 5.2.15 on 2026-06-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_submissionfiles_extracted_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionfiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submission_files/'),
        ),
        migrations.AlterField(
            model_name='submissionfiles',
            name='file_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
