# Generated by Django 5.2.15 on 2026-06-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_submissionfiles_extracted_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderfiles',
            name='file_category',
            field=models.CharField(blank=True, choices=[('boq', 'BOQ'), ('drawing', 'Drawing'), ('specification', 'Specification'), ('other', 'Other')], max_length=20),
        ),
    ]
