# Generated by Django 5.2.15 on 2026-06-28 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_users_email'),
        ('api', '0007_submissionfiles_file_alter_submissionfiles_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionfiles',
            name='need_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenderfiles',
            name='need_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenders',
            name='analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('invalid_documents', 'Invalid Documents')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='tenders',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenders',
            name='awarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tendersubmissions',
            name='need_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenderfiles',
            name='file_category',
            field=models.CharField(blank=True, choices=[('boq', 'BOQ'), ('drawing', 'Drawing'), ('specification', 'Specification'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tendersubmissions',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_submissions', to='account.contractorprofiles'),
        ),
    ]
