# Generated by Django 5.2.15 on 2026-06-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_submissionfiles_need_review_tenderfiles_need_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tendersubmissions',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='under_review', max_length=20),
        ),
    ]
