# Generated by Django 5.2.15 on 2026-06-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_tendersubmissions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionfiles',
            name='file_category',
            field=models.CharField(choices=[('technical', 'Technical Proposal'), ('financial', 'Financial Proposal'), ('boq', 'BOQ'), ('certificates', 'Certificates & License')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
