# Generated by Django 5.2.15 on 2026-07-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_submissionfiles_file_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqitems',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boqitems',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
