# Generated by Django 5.2.15 on 2026-07-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_boqitems_quantity_alter_boqitems_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqprice',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
