# Generated by Django 5.2.15 on 2026-07-07 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_users_email'),
        ('api', '0013_tenders_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenders',
            name='awarded_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_tenders', to='account.contractorprofiles'),
        ),
    ]
