import OwnerLayout from "../components/OwnerLayout";

function Reports() {
  const reports = [
    {
      icon: "bi-file-earmark-text",
      title: "Tender Evaluation Report",
      type: "PDF",
      color: "red",
      desc: "Complete contractor comparison with AI scores, risk analysis, and final rankings",
      meta: "18 pages · 2.4 MB · Jun 10, 2026",
    },
    {
      icon: "bi-table",
      title: "BOQ Comparison Matrix",
      type: "Excel",
      color: "green",
      desc: "Side-by-side comparison of all contractor BOQ pricing across 247 line items",
      meta: "12 sheets · 1.8 MB · Jun 10, 2026",
    },
    {
      icon: "bi-cpu",
      title: "AI Risk Analysis Report",
      type: "PDF",
      color: "purple",
      desc: "Detailed risk assessment, anomaly detection results, and compliance checklist",
      meta: "9 pages · 1.1 MB · Jun 10, 2026",
    },
    {
      icon: "bi-stars",
      title: "Executive Summary",
      type: "PDF",
      color: "orange",
      desc: "AI-generated 2-page brief for stakeholders: top recommendation, key findings, next steps",
      meta: "2 pages · 0.5 MB · Jun 10, 2026",
    },
    {
      icon: "bi-grid",
      title: "Contractor Tracking Sheet",
      type: "Excel",
      color: "blue",
      desc: "All contractor submission statuses, scores, contact info, and document checklist",
      meta: "4 sheets · 0.9 MB · Jun 10, 2026",
    },
  ];

  return (
    <OwnerLayout activePage="reports">
      <section className="reports-content">
        <div className="reports-header">
          <h2>Report Export</h2>
          <p>
            Download AI-generated evaluation reports for Eastfield Tower Complex
          </p>
        </div>

        <div className="executive-report-card">
          <div className="executive-report-top">
            <div className="report-title-box">
              <div className="report-ai-icon">
                <i className="bi bi-stars"></i>
              </div>

              <div>
                <h5>AI-Generated Executive Summary</h5>
                <p>BuildTender AI v3.2 · Generated Jun 10, 2026</p>
              </div>
            </div>

            <button className="download-main-btn">
              <i className="bi bi-download"></i>
              Download PDF
            </button>
          </div>

          <div className="summary-preview">
            <h5>Executive Summary — Eastfield Tower Complex</h5>
            <p>
              Tender Evaluation Complete | Generated by BuildTender AI | June 10,
              2026
            </p>

            <h6>Key Findings</h6>
            <p>
              12 proposals evaluated across price, technical quality, experience,
              and compliance criteria.
            </p>

            <ul>
              <li>Recommended Contractor: AlSalam Construction</li>
              <li>Highest technical score (91/100) and compliance rating (96/100)</li>
              <li>Strong trust score (88/100) based on 47 completed projects</li>
              <li>Competitive bid at $4.2M within market range</li>
              <li>
                Critical risk identified: Peak Contracting LLC's bid is 34% below
                market average.
              </li>
              <li>
                Document gaps: 2 contractors have outstanding documentation issues.
              </li>
            </ul>

            <h6>Recommended Next Steps</h6>
            <ol>
              <li>Proceed to contract negotiation with AlSalam Construction</li>
              <li>Formally request justification from Peak Contracting or disqualify</li>
              <li>
                Request updated certifications from Meridian Builders before final
                decision
              </li>
              <li>Issue award letter by August 1, 2026</li>
            </ol>
          </div>
        </div>

        <h5 className="available-title">Available Reports</h5>

        <div className="reports-list">
          {reports.map((report) => (
            <div className="report-row" key={report.title}>
              <div className={`report-file-icon ${report.color}`}>
                <i className={`bi ${report.icon}`}></i>
              </div>

              <div className="report-info">
                <h5>
                  {report.title}
                  <span className={report.color}>{report.type}</span>
                </h5>
                <p>{report.desc}</p>
                <small>
                  <i className="bi bi-clock"></i> {report.meta}
                </small>
              </div>

              <div className="report-actions">
                <button className="preview-btn">
                  <i className="bi bi-eye"></i>
                </button>

                <button className="download-report-btn">
                  <i className="bi bi-download"></i>
                  Download
                </button>
              </div>
            </div>
          ))}
        </div>

        <div className="download-all-box">
          <div>
            <h5>Download All Reports</h5>
            <p>All 5 reports bundled as a ZIP file · 6.7 MB total</p>
          </div>

          <button className="download-main-btn">
            <i className="bi bi-download"></i>
            Download All (ZIP)
          </button>
        </div>
      </section>
    </OwnerLayout>
  );
}

export default Reports;